### ISSUE TITLE
Missing 'dbutils'

### ISSUE THREAD

**Issue by CHesketh76** [databrickslabs/dolly#103]
only appears in the 'train_dolly.py' and it is not clear where or if it is imported.

**Comment by srowen** [comment]
Ignore it if not running on Databricks. It's there to let you select the model size, etc from widgets. You can just replace them with your choice of value in the script

**Comment by wilac-pv** [comment]
python train_dolly.py

^[[ATraceback (most recent call last):
  File "train_dolly.py", line 89, in <module>
    dbutils.widgets.combobox("input_model", DEFAULT_INPUT_MODEL, SUGGESTED_INPUT_MODELS, "input_model")
NameError: name 'dbutils' is not defined

**Comment by srowen** [comment]
As I say above, just don't use this if you are not on Databricks. Delete it. Set the variables this configures to the value you want directly.
