### ISSUE TITLE
Contributing some fixes to the dataset

### ISSUE THREAD

**Issue by dvsrepo** [databrickslabs/dolly#105]
Hi! 

Congrats on this cool effort!

As part of the cleaning up of [translated versions](https://huggingface.co/datasets/argilla/databricks-dolly-15k-multilingual) of the dataset, we have identified some minor, but relevant, issues that can be easily fixed. I wonder if we could contribute the fixed version of the dataset with a PR so the changes/diff is clear or we should just keep an English-cleaned version ourselves. Our experience with past efforts like Alpaca is that there were several projects providing cleaned versions but many people kept using the original. This dataset is MUCH cleaner but we'd love to contribute back.

In particular, the first issue is about footnotes and references, originated by copy/pasting Wikipedia articles. We have generated a cleaned version which:

- Removes the references (e.g., [5], [30], [a]) from the `context` field of 2100 examples. Although this might be harmless I think it could help in reducing the size of context values and in general making the models read cleaner text.
- Removes the references from the `response` field of 187 examples. This is much smaller but more problematic, as it will tell instruction-following models that it's fine to make up some references in the response.

I'd love to send a PR for your review of the original file or if you are interested on keeping a separate file also happy to do that.

**Comment by srowen** [comment]
@matthayes is going to collect this feedback and get it into a larger batch update, thank you
