### ISSUE TITLE
No module named 'torch._six'

### ISSUE THREAD

**Issue by leojames** [databrickslabs/dolly#108]
Python 3.10 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/dolly/anaconda3/envs/dolly/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 724, in pipeline
    framework, model = infer_framework_load_model(
  File "/export/dolly/anaconda3/envs/dolly/lib/python3.10/site-packages/transformers/pipelines/base.py", line 229, in infer_framework_load_model
    _class = getattr(transformers_module, architecture, None)
  File "/export/dolly/anaconda3/envs/dolly/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1084, in __getattr__
    value = getattr(module, name)
  File "/export/dolly/anaconda3/envs/dolly/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1083, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/export/dolly/anaconda3/envs/dolly/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1095, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt_neox.modeling_gpt_neox because of the following error (look up to see its traceback):
No module named 'torch._six'

deepspeed verion is wrong ?

**Comment by srowen** [comment]
You probably have an incompatible old pytorch version. What are you using? are you installing the requirements.txt as shown in this repo?

**Comment by hyb1234hi** [comment]
I also have the same problem

**Comment by srowen** [comment]
What torch version do you have? maybe that needs to be pinned

**Comment by subramgo** [comment]
model, tokenizer = load_model_tokenizer_for_generate(default_model)
The above line raises this error. Error at

File /opt/conda/envs/py39/lib/python3.9/site-packages/deepspeed/runtime/utils.py:19
     18 import torch
---> 19 from torch._six import inf
     20 from deepspeed import comm as dist

ModuleNotFoundError: No module named 'torch._six'

The error traces to deepspeed 0.8.0 version.

The versions installed. 
accelerate>=0.12.0
click==8.0.3
datasets==2.8.0
deepspeed==0.8.0
transformers[torch]==4.25.1
langchain>=0.0.139

**Comment by srowen** [comment]
I updated the list of requirements to require later deepspeed, and fix a version of torch. Try again?

**Comment by subramgo** [comment]
Yes the updated torch and deepspeed versions fixed _six import problem. 
. Since cuda was pre-installed, after installing the latest version of torch and deepspeed versions mentioned in requirements.txt,  got the error

OSError: /opt/conda/envs/py39/lib/python3.9/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtGetStatusString version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

Had to uninstall nvidia-cublas-cu11, to get rid of this error. Not sure if this is a conda issue or a torch issue.

Now got the following error,

OSError: Unable to load weights from pytorch checkpoint file for 'dolly-v2-12b/pytorch_model.bin' at 'dolly-v2-12b/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

Looking at it. Thanks for your help.

**Comment by srowen** [comment]
You probably don't quite have the right cublas version for your CUDA? The training script shows the right installs for CUDA 11.3 and 11.7. I'm not sure where you're loading from but just path the model name in HF

**Comment by subramgo** [comment]
I am loading the model from a local folder. The tokernizer is loading,however the model fails with 
SError: Unable to load weights from pytorch checkpoint file for 'dolly-v2-12b/pytorch_model.bin' at 'dolly-v2-12b/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

Even loading from hugging face by passing databricks/dolly-v2-12b fails with the same error.

**Comment by srowen** [comment]
Hm, I can't reproduce that. Start over with exactly the example on the repo page?

**Comment by leojames** [comment]
> You probably have an incompatible old pytorch version. What are you using? are you installing the requirements.txt as shown in this repo?

yes i  run pip install -r requirements.txt  
but i found that the deepspeed has change  the code resently 
you anwser other person  
I updated the list of requirements to require later deepspeed, and fix a version of torch. Try again?

later i will try it again    

thx
