### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by ibrahim737701** [databrickslabs/dolly#109]
```
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\mohammad.ibrahim-st/.cache\huggingface\hub\models--databricks--dolly-v2-3b\snapshots\9c82082015ad144fe64317dae8b0d6e4ee78a732\pytorch_model.bin' at 'C:\Users\mohammad.ibrahim-st/.cache\huggingface\hub\models--databricks--dolly-v2-3b\snapshots\9c82082015ad144fe64317dae8b0d6e4ee78a732\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("databricks/dolly-v2-3b", padding_side="left")
model = AutoModelForCausalLM.from_pretrained("databricks/dolly-v2-3b", device_map="auto", trust_remote_code=True, torch_dtype=torch.bfloat16)
```

**Comment by srowen** [comment]
I'm guessing you have an old version of pytorch or transformers. Please install the requirements as shown in this repo's requirements.txt

**Comment by ibrahim737701** [comment]
I have the all the latest requirements installed, it's still showing this error

**Comment by ibrahim737701** [comment]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1490: character maps to <undefined>

This is also coming

**Comment by srowen** [comment]
What version of torch and transformers do you have, just to be sure? it could be that we need to pin torch

**Comment by srowen** [comment]
Try again - Updated the requirements to include torch, and fix some newer versions

**Comment by ibrahim737701** [comment]
torch                        1.13.1
torchaudio                   0.13.1
torchvision                  0.14.1
transformers                 4.25.1

I initially had torch 2.0 but i suspected dolly doesn't support it

**Comment by srowen** [comment]
More likely deepspeed, the base model, etc but yeah that's fairly new and there is a lot of tooling that is deeply connected to torch here. It works now?
