### ISSUE TITLE
ValueError: Your setup doesn't support bf16/gpu.

### ISSUE THREAD

**Issue by yinwangsong** [databrickslabs/dolly#11]
I run the notebook on 8 V100 GPUs, but an error occured:
```
  File "<string>", line 105, in __init__
  File "/databricks/python/lib/python3.9/site-packages/transformers/training_args.py", line 1098, in __post_init__
    raise ValueError(
ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0
```
I changed "bf16" to "fp16" in ds_z3_bf16_config.json, but nothing happen...

**Comment by matthayes** [comment]
You might need to also change these settings: https://github.com/databrickslabs/dolly/blob/master/training/trainer.py#L182

**Comment by yinwangsong** [comment]
Thanks, this works.
