### ISSUE TITLE
[wrong] train_ Dolly file description is incorrect

### ISSUE THREAD

**Issue by Galaxy-Ding** [databrickslabs/dolly#110]
`# MAGIC (e.g. [pythia-2.8b](https://huggingface.co/EleutherAI/pythia-6.9b),`
it should be changed like :
`# MAGIC (e.g. [pythia-2.8b](https://huggingface.co/EleutherAI/pythia-2.8b),`

**Comment by srowen** [comment]
Good catch, I'll change that
