### ISSUE TITLE
OSError: databricks/dolly-v2-3b does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.

### ISSUE THREAD

**Issue by ibrahim737701** [databrickslabs/dolly#117]
import torch
from instruct_pipeline import InstructionTextGenerationPipeline
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("databricks/dolly-v2-3b", padding_side="left")
model = AutoModelForCausalLM.from_pretrained("databricks/dolly-v2-3b", device_map="auto", torch_dtype=torch.bfloat16, from_tf = True)

generate_text = InstructionTextGenerationPipeline(model=model, tokenizer=tokenizer)

**Comment by srowen** [comment]
Hm, that works for me. Clear your HF cache and run again or something? or add "model=" before the model name to be sure it's interpreting that correctly

**Comment by ibrahim737701** [comment]
It's still not working i tried both
