### ISSUE TITLE
How can I run the train_dolly.py file?

### ISSUE THREAD

**Issue by senthilrajd** [databrickslabs/dolly#121]
This train_dolly.py has some lines based on the python notebook. I would like to directly run it in the terminal. Can you help me on this?

Another question: Is the g5.24xlarge or g5.12xlarge enough to train the model with my own data? How much time will it take to train this model with my data.

**Comment by srowen** [comment]
It's a notebook you can load in Databricks, but you can also just lightly modify it for elsewhere. The shell commands you have to run separately, and the dbutils part you just need to ignore and set variables directly. That should be about it.

Please see the README for notes on how to train on those instances.

**Comment by Lednik7** [comment]
I tried to run EleutherAI/pythia-2.8b on Kaggle with 2*T4, but got a RAM overflow error. Can you help me?

https://www.kaggle.com/code/mygaps/dolly-ru-train

**Comment by srowen** [comment]
Again, see the README. https://github.com/databrickslabs/dolly#training-on-other-instances
No, T4s aren't enough.
