### ISSUE TITLE
Getting weird responses with my fine-tuned model

### ISSUE THREAD

**Issue by jackyyanggp** [databrickslabs/dolly#136]
I was able to fine-tuned the model with custom dataset but the responses are often times weird:
1. it always contain my original prompt which I don't need
2. sometimes it can have many repeated sentences/phrases
3. takes about 30s to generate a response on p3dn.24xlarge, which seems too long and not normal?

Thanks for the help!

response function used:
```
from transformers import pipeline
import torch
# Function to generate a language model response
def generate_response(text):
    instruct_pipeline = pipeline(
        task="text-generation", 
        model="dollymaster/dolly__1__0426T1946",# can be custom training directory or the original dolly2 model
        torch_dtype=torch.bfloat16, 
        trust_remote_code=True, 
        device_map="auto",
    #     eos_token_id = 0
        pad_token_id=0,
        # max_length = 128,
        max_new_tokens = 256
    )
    return instruct_pipeline(text)
```

libraries env:
datasets==2.10.0
langchain==0.0.2
deepspeed==0.9.0
accelerate==0.16.0
click==8.0.4
transformers[torch]==4.28.1
torch==1.13.1
tensorboardX==2.6

**Comment by matthayes** [comment]
>it always contain my original prompt which I don't need

The standard `text-generation` pipeline will output the original prompt with the completion appended.  From your code above it appears this might be what is being used.  dolly v2 uses a [custom pipeline](https://huggingface.co/databricks/dolly-v2-12b/blob/main/instruct_pipeline.py), which would be used if you are referencing one of the dolly v2 models.  But for your model I'm assuming that would not be used.

**Comment by matthayes** [comment]
>sometimes it can have many repeated sentences/phrases

It's hard to know what could be causing this.  It may have to do with the custom dataset.  You can also try using different generation parameters.  The dolly v2 pipeline sets [certain defaults](https://huggingface.co/databricks/dolly-v2-12b/blob/main/instruct_pipeline.py#L62) which tend to produce good results for the model.  There are other options you can try, like penalizing repeats.

**Comment by matthayes** [comment]
>takes about 30s to generate a response on p3dn.24xlarge, which seems too long and not normal?

I haven't used that particular machine so I'm not sure what would be normal for it.  However looking at your `generate_response` function it seems that the model loading is happening in the same function.  So part of the time you are seeing could be from model loading.  I would try moving the `pipeline` call out and measuring each individual invocation of it.  You can also try lowering `max_new_tokens` so it generates fewer tokens (= less time spent generating). There was also an update recently to the dolly v2 model configs to set `use_cache` to True, which also speeds up generation a bit.  I'm not sure if you are getting that new setting.

**Comment by jackyyanggp** [comment]
helpful tips! using your original code along with the new cache setting is much more faster to generate response. However, after running it once and restart the kernel, it takes a long time to run and gets stuck at `load_model_tokenizer_for_generate()` for the second time, with no error. Does it change any files? 
```
from training.generate import generate_response, load_model_tokenizer_for_generate

model, tokenizer = load_model_tokenizer_for_generate(local_output_dir)

instructions = [
    "Write a love letter to Edgar Allan Poe.",
    "Write a tweet announcing Dolly, a large language model from Databricks.",
    "I'm selling my Nikon D-750, write a short blurb for my ad.",
    "Explain to me the difference between nuclear fission and fusion.",
    "Give me a list of 5 science fiction books I should read next.",
]

# Use the model to generate responses for each of the instructions above.
for instruction in instructions:
    response = generate_response(instruction, model=model, tokenizer=tokenizer)
```

**Comment by jackyyanggp** [comment]
> @matthayes thanks! helpful tips! using your original code along with the new cache setting is much faster to generate response. However, after running it once and restarting the kernel, it takes a long time to run and gets stuck at `load_model_tokenizer_for_generate()` for the second time, with no error. Does it change any files?
> 
> ```
> from training.generate import generate_response, load_model_tokenizer_for_generate
> 
> model, tokenizer = load_model_tokenizer_for_generate(local_output_dir)
> 
> instructions = [
>     "Write a love letter to Edgar Allan Poe.",
>     "Write a tweet announcing Dolly, a large language model from Databricks.",
>     "I'm selling my Nikon D-750, write a short blurb for my ad.",
>     "Explain to me the difference between nuclear fission and fusion.",
>     "Give me a list of 5 science fiction books I should read next.",
> ]
> 
> # Use the model to generate responses for each of the instructions above.
> for instruction in instructions:
>     response = generate_response(instruction, model=model, tokenizer=tokenizer)
> ```

to be more specific, it's stuck at `model = AutoModelForCausalLM.from_pretrained(
        pretrained_model_name_or_path, device_map="auto", torch_dtype=torch.bfloat16, trust_remote_code=True)`. worked the first time I finished fine-tuning but started having this issue after I restart the instance. loading the tokenizer is fine.
@matthayes @srowen any help would be appreciated!

**Comment by srowen** [comment]
Are you OOM? maybe restarting the kernel wasn't enough somehow or something else is still attached. From this not sure what else could be the issue.

**Comment by jackyyanggp** [comment]
> Are you OOM? maybe restarting the kernel wasn't enough somehow or something else is still attached. From this not sure what else could be the issue.

@srowen hmm nope, it's not using any GPU at all actually at this step `model = AutoModelForCausalLM.from_pretrained( pretrained_model_name_or_path, device_map="auto", torch_dtype=torch.bfloat16, trust_remote_code=True)`

**Comment by srowen** [comment]
I was thinking swapping or something. Check all your VM stats to see what might be going on, like is it even busy on the CPU

**Comment by jackyyanggp** [comment]
@srowen CPU is pretty quiet too...
![image](https://user-images.githubusercontent.com/74266286/235039521-6f1bfc8a-6239-4d46-82f1-026e152fe7d7.png)

**Comment by matthayes** [comment]
Have you tried restarting the machine? Maybe restarting the kernel isn’t enough. Since it worked the first time before restarting the kernel it seems there isn’t an issue with the model. This seems like perhaps a setup or library issue.
