### ISSUE TITLE
Running dolly-2.0-3b on a local machine

### ISSUE THREAD

**Issue by MoShiha** [databrickslabs/dolly#141]
Any success running the smallest Dolly 2.0 on a local machine? I failed to do so on an Apple M1 MacBook. I understand this might not necessarily be a good enough to run the model but just checking in case I might be doing something wrong.

**Comment by srowen** [comment]
Probably not; search other issues here for comments. You need a GPU, and won't really be able to access the GPU on a Mac with this.
