### ISSUE TITLE
[Feature] Logprobs 

### ISSUE THREAD

**Issue by xingdi-eric-yuan** [databrickslabs/dolly#143]
Hi, thanks for sharing the code and models! May I ask what's an easy way to obtain the logprobs of each chosen tokens (not necessarily the entire vocab) during generation? Thanks!

**Comment by srowen** [comment]
I haven't tried this, but I think you can just use compute_transition_scores for this in the transformers API, like at https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationMixin.compute_transition_scores.example

**Comment by xingdi-eric-yuan** [comment]
Thank you @srowen , I will try and report back.

**Comment by xingdi-eric-yuan** [comment]
Just to report back, `compute_transition_scores` is exactly what I needed. Thanks for the suggestion. 
One thing worth mentioning is that, when looking at logprobs per token (rather than strings that we can strip), one needs to change [this](https://huggingface.co/databricks/dolly-v2-3b/blob/main/instruct_pipeline.py#L180) to `response_pos + 2` because there is an extra `\n` after the response token ([as defined here](https://huggingface.co/databricks/dolly-v2-3b/blob/main/instruct_pipeline.py#L29)).
