### ISSUE TITLE
Cluster configurations

### ISSUE THREAD

**Issue by dineshreddy221** [databrickslabs/dolly#148]
Hi,

I am trying to build own dolly by changing the dataset and running the train_dolly.py application with EleutherAI/pythia-2.8b on cluster configurations in databricks, 56GB Memory 1GPU. 

Thank you in advance, is this configuration works to train the model.

**Comment by srowen** [comment]
It depends on what GPU you have and the GPU memory, mostly. For the 3B model, most modern GPUs are fine. See notes at https://github.com/databrickslabs/dolly#getting-started-with-training

**Comment by dineshreddy221** [comment]
Thank you for the information..
