### ISSUE TITLE
Dolly keeps generating answers despite the instructions

### ISSUE THREAD

**Issue by murtasy** [databrickslabs/dolly#149]
Dolly model keeps on answering questions that are not part of the input documents. For example, I can ask: why do Canadians play hockey? where is Toronto? where are brothels in Toronto? It keeps answering all of these questions instead of saying I do not know. Here is the prompt 

template = """You are a chatbot having a conversation with a human. Your are asked to answer gardening questions and help cultivating plants.
Given the following extracted parts of a long document and a question, answer the user question. If you don't know, say that you do not know.

I did try to change it a bit but still does not work. How to fix this?

template = """You are a chatbot having a conversation with a human. Your are asked to answer gardening questions and help cultivating plants.
Answer from the following documents otherwise say I do not know."""

We also tried this scoring based method on embeddings of vector search. In short, it doesn't work too. We can set a threshold on score of similarity search before sending to the model but there is always a way to hack it by combining words. Model keeps on generating hallucinating answers. Dolly needs some more fine tuning.

**Comment by srowen** [comment]
Same as https://github.com/databricks-demos/dbdemos/issues/28

I'm not quite sure what you're asking. You can extract the log probability of a response from a model and you can decide whether the model feels sure enough about it to use it, or else decline to respond. The model does not do that; it is supplying responses.

**Comment by matthayes** [comment]
This prompt is in a format different from what Dolly was fine tuned with: https://github.com/databrickslabs/dolly/blob/master/training/consts.py#L40

The model will usually not perform well with a different prompt format. 

Also, the model was not fine tuned with turn-taking conversation data. It will do better with a single instruction and response.

**Comment by murtasy** [comment]
Thank you for the reply. The prompt above I used is extracted from dbdemos chatbot project provided by Databricks. We have tried with single instruction too it is giving the same output.

So based on above: https://github.com/databrickslabs/dolly/blob/master/training/consts.py 
Prompt for inferencing for QA should be : 
PROMPT_FOR_GENERATION_FORMAT = """{intro}

{instruction_key}
{instruction}

{response_key}
""".format(
    intro=INTRO_BLURB,
    instruction_key=INSTRUCTION_KEY,
    instruction="{instruction}",
    response_key=RESPONSE_KEY,
)
. Here inro_blurb can be ""Below is an instruction that describes a task. Write a response that appropriately completes the request."

From Databricks dolly data set I got the following example. Please correct me if I am mapping it correctly for QA from a given doc fro remaining fields. Instruction key above will be instruction below. Instruction will be context below and respond key above will be category=closed_qa below.

{"instruction": "What is linux Bootloader",
 "context": "A bootloader, also spelled as boot loader or called boot manager and bootstrap loader, is a computer program that is responsible for booting a computer.\n\nWhen a computer is turned off, its software including operating systems, application code, and data\u200d\u2014\u200cremains stored on non-volatile memory. When the computer is powered on, it typically does not have an operating system or its loader in random-access memory (RAM). The computer first executes a relatively small program stored in read-only memory (ROM, and later EEPROM, NOR flash) along with some needed data, to initialize RAM (especially on x86 systems), to access the nonvolatile device (usually block device, eg NAND flash) or devices from which the operating system programs and data can be loaded into RAM.\n\nSome earlier computer systems, upon receiving a boot signal from a human operator or a peripheral device, may load a very small number of fixed instructions into memory at a specific location, initialize at least one CPU, and then point the CPU to the instructions and start their execution. These instructions typically start an input operation from some peripheral device (which may be switch-selectable by the operator). Other systems may send hardware commands directly to peripheral devices or I/O controllers that cause an extremely simple input operation (such as \"read sector zero of the system device into memory starting at location 1000\") to be carried out, effectively loading a small number of boot loader instructions into memory; a completion signal from the I/O device may then be used to start execution of the instructions by the CPU.\n\nSmaller computers often use less flexible but more automatic boot loader mechanisms to ensure that the computer starts quickly and with a predetermined software configuration. In many desktop computers, for example, the bootstrapping process begins with the CPU executing software contained in ROM (for example, the BIOS of an IBM PC or an IBM PC compatible) at a predefined address (some CPUs, including the Intel x86 series are designed to execute this software after reset without outside help). This software contains rudimentary functionality to search for devices eligible to participate in booting, and load a small program from a special section (most commonly the boot sector) of the most promising device, typically starting at a fixed entry point such as the start of the sector.", 
 "response": "A bootloader is a program written in machine code that loads the operating system into RAM during the boot process.",
  "category": "closed_qa"}

I am trying to understand what is correct prompt for dolly for QA.

**Comment by yifanniemanu** [comment]
Hi Dolly team. Goodday. I also encountered this problem by following this section "prompt_for_generation_format": https://github.com/databrickslabs/dolly/blob/master/training/consts.py#L64 
with all the correct starting markers ### for instruction and response. In my instruction, I gave some context sentences and specified "if you can't find the answers from the context, please do not answer". But it still tries to answer the question with random and wrong hallucinations learned from the pre-trained corpus.

Is there a way in the prompt to tell it to stop answering if it cannot find the answers from the context sentences?

Thanks.

**Comment by srowen** [comment]
You can try that in the prompt, but it doesn't guarantee it will do that. You can get the log prob of the response and decide when the model isn't that sure about the response and not use the answer: https://github.com/databrickslabs/dolly/issues/143 This also doesn't guarantee anything but worth a try.
