### ISSUE TITLE
Training time (p4d.24xlarge)

### ISSUE THREAD

**Issue by asfires** [databrickslabs/dolly#15]
Anyone know how long Dolly took to train on a p4d.24xlarge instance? I know that Alpaca took around 3 hours to train on an identical instance, so now I'm wondering how long it takes to train Dolly. Trying to gauge how much this will cost.

**Comment by matthayes** [comment]
I haven’t tried on that particular instance, but on Standard_ND96asr_v4, which also has 8 A100s, from what I’ve seen it usually takes just under 30 minutes, not including downloading the initial model.

**Comment by asfires** [comment]
Wow. Did you do anything in particular to optimize training efficiency compared to how they trained Alpaca? They noted in their announcement that it could be done in under three hours with improved training efficiency, so I’m just curious to know what you did to improve on that unless you think the dramatically reduced training time for Dolly is a function of something else entirely, although I can’t think of what else it might be given that it’s the same training data.

**Comment by bingjie3216** [comment]
I would say the epoch number might be different, 1 epoch for dolly vs 3 epochs for alpaca

**Comment by hsuyab** [comment]
@matthayes did you train with `LORA` or in `bf16` or with `float32`?

**Comment by srowen** [comment]
From the code - not using LoRA, using bf16, 1 epoch

**Comment by matthayes** [comment]
Sorry I haven't done a comparison yet of how they're training relative to us so I'm not sure exactly what accounts for the difference in runtime.

**Comment by opyate** [comment]
Using [g5.12xlarge](https://aws.amazon.com/ec2/instance-types/g5/) (4 x A10G) and the [adjusted config](https://github.com/databrickslabs/dolly#a10-gpus-1), the 3b model takes 5.6 hours.
