### ISSUE TITLE
repetition sentences/phrases in response

### ISSUE THREAD

**Issue by jackyyanggp** [databrickslabs/dolly#150]
Hi, how how I penalize the model for generating repetition of sentences/phrases in response, if I want to edit the current custom "generate.py" instead of the transformer pipeline library? Thanks!

**Comment by srowen** [comment]
See https://huggingface.co/blog/how-to-generate
You don't need to use generate.py but you're welcome to start from that.
This is just a matter of using transformers settings, not particularly specific to this model.
