### ISSUE TITLE
TypeError:pipeline() missing 1 required positional argument :'task'

### ISSUE THREAD

**Issue by Minjuner-97** [databrickslabs/dolly#151]
from transformers import pipeline
import torch

instruct_pipeline = pipeline(model="databricks/dolly-v2-12b", torch_dtype=torch.float16, trust_remote_code=True, device_map="auto")

GPU：1*V100 
transformers:4.3.0
torch:1.2.0
cuda:10.0
cudnn:10.0-7.6.3

----------------------------------------------------------------------------------------------------------------------------

result：
TypeError:pipeline() missing 1 required positional argument :'task'

How can I resolve it ?

**Comment by srowen** [comment]
Your version of transformers is quite old. As you see in the model card and repo here, you should use 4.28 or later.
