### ISSUE TITLE
Running deepspeed in subdirectory

### ISSUE THREAD

**Issue by BrandenOlson** [databrickslabs/dolly#153]
Hello,

I'm not sure if this is a Databricks issue, a Deepspeed issue, or lack of my own understanding, but here goes:

The [`train_dolly` notebook](https://github.com/databrickslabs/dolly/blob/master/train_dolly.py) currently resides in the top-level `dolly` directory. This notebook includes a [`deepspeed` command](https://github.com/databrickslabs/dolly/blob/master/train_dolly.py#L161) which passes the [`--module training.trainer` argument](https://github.com/databrickslabs/dolly/blob/master/train_dolly.py#L162). Running as-is in Databricks works fine for me. 

However, if I move this notebook to a subdirectory of `dolly` (e.g. to [`dolly/training`](https://github.com/databrickslabs/dolly/tree/master/training), I get the following error:
```
python: Error while finding module specification for 'training.trainer' (ModuleNotFoundError: No module named 'training')
```

Any advice on how to adjust the code for this to work?

Also, it seems like it's possible to invoke `deepspeed` as a Python package. What is the rationale to run the command line binary instead?

**Comment by julianfaraone** [comment]
Can't you just add  "export PYTHONPATH=<Enter path to dolly>" ? so that it can find the training folder?

**Comment by srowen** [comment]
Right, because then you put the notebook alongside trainer.py, and you are still telling it to look for training.trainer, but it is not in a submodule. Why change that though?

You can write calls to deepspeed inside Python code, yes. I think it's easier to have it run a standalone training script as it requires no code modification otherwise, and the training script could be used with other packages like accelerate. no strong reason to do it either way here, just was simpler. I think it's also a little easier then to make this work across multiple machines this way too, as the script will handle ssh-ing into other machines and running the code

**Comment by BrandenOlson** [comment]
Ok, as clunky as it is, I was able to get it working via setting
```
PYTHON_PATH = "<path-to-dolly>:$PYTHONPATH"
```

and then running

```
! PYTHONPATH={PYTHON_PATH} deepspeed \
    {num_gpus_flag} \
    --module mlsaas.scripts.llm.trainer \
    ...
```

(For some reason, running `! export PYTHONPATH = ...` doesn't seem to actually update the environment variables).

It seems like Databricks is able to update the python paths in the notebooks to include the Repos. Not sure why it doesn't work at the command line level 🤔

**Comment by BrandenOlson** [comment]
> Right, because then you put the notebook alongside trainer.py, and you are still telling it to look for training.trainer, but it is not in a submodule. Why change that though?

I'm creating a similar notebook for my use case, but my team organizes the code so that we don't have notebooks at the top level. I think my fix above will have to do the trick for now.

> You can write calls to deepspeed inside Python code, yes. I think it's easier to have it run a standalone training script as it requires no code modification otherwise, and the training script could be used with other packages like accelerate. no strong reason to do it either way here, just was simpler. I think it's also a little easier then to make this work across multiple machines this way too, as the script will handle ssh-ing into other machines and running the code

Thanks for the clarification!
