### ISSUE TITLE
is train_dolly.py inference only?

### ISSUE THREAD

**Issue by julianfaraone** [databrickslabs/dolly#154]
Im running this training run on a separate environment to Databricks. 

I have removed all the instances of "dbutils" and have run the train_dolly.py using 

`deepspeed train_dolly.py --module training.trainer --deepspeed config/ds_z3_bf16_config.json`

however this just performs inference. What is the command for training? or where exactly is the trainer invoked?

**Comment by srowen** [comment]
No, that script is for training, hence the name. What are you seeing that makes you think otherwise?
deepspeed is running a training script that uses trainer.

**Comment by julianfaraone** [comment]
Thanks. I solved this by removing the "train_dolly.py" in the command with deepspeed above. Then the training ran. I.e. I used.
`deepspeed --module training.trainer --deepspeed config/ds_z3_bf16_config.json`

**Comment by srowen** [comment]
Oh, yes, train_dolly.py is the top level runner script, not the core training loop that deepspeed runs. What you have is what was already in the provided example, yes
