### ISSUE TITLE
Can I take a large corpus of text not necessary in the form of instructions and response, and just fine tune Dolly?

### ISSUE THREAD

**Issue by abhisheksgumadi** [databrickslabs/dolly#155]
I have looked at the training code. I have a large corpus of domain specific text. Could be emails and general documents. These are not in any instruction and response format.

I am looking to find tuning Dolly as a generative model so if I write a question later it will just complete the text using the generate method.

Is it possible to fine tune this way instead of using only a question answer format CSV file as shown in the datasets now? 

Any suggestions will be appreciated urgently.

**Comment by srowen** [comment]
Do you mean you want to answer questions? If it's just answering questions from info in that corpus, then no you do not need to fine-tune. Feed relevant chunks of text to the model as context with your question. This is what the example at https://www.dbdemos.ai/demo.html?demoName=llm-dolly-chatbot does.

The model is not actually fine-tuned on questions and answers, but strings - you can see this in the training script where question-context-response tuples are flattened into a string. So 'yes' this does not require question-answer data, but, it seems like you do want a model that answers questions, and there is an easier way to do that.

**Comment by abhisheksgumadi** [comment]
Thanks a lot. Firstly, super awesome work with Dolly! May I ask how long of a context can it handle please?

**Comment by srowen** [comment]
2048 tokens

**Comment by abhisheksgumadi** [comment]
Thanks! Brilliant answers and great work by the team.

**Comment by abhisheksgumadi** [comment]
Sorry I have a question related to the above chat to make sure I use Dolly in it's best potential.

If I were to fine tune Dolly using general text as strings without having them as questions and answers, once trained, would I still be able to use it in a question answer mode relevant to my corpus on which it has been trained?

I am sure I can write a sentence like "Tell me something about tennis" given that the corpus is sports related and it will complete by explaining what tennis is.

However would I still be able to ask questions with a question mark about my corpus?

Thanks so much for taking the time to answer my questions.

Abhishek Shivkumar

**Comment by srowen** [comment]
You can try, but, the more you fine tune it on just strings, the more you are asking it to continue strings in the same way, and if the strings aren't questions followed by answers, then it's not learning to follow questions with answers. This is true of any model. The point of Dolly was to fine-tune Pythia, which is mostly trained on just strings of English text, to specifically learn to follow instructions with responses.

Again: see my answer above. You generally do _not_ have to fine tune a model just to make it answer questions over a different corpus than it was fine-tuned on.

**Comment by abhisheksgumadi** [comment]
Thank you for the time to answer this question.
