### ISSUE TITLE
How to use the model for chatting?

### ISSUE THREAD

**Issue by yinwangsong** [databrickslabs/dolly#16]
I have finetuned the model and got the checkpoint, what should I do to use the model for chatting?

**Comment by youkaichao** [comment]
@yinwangsong I write a script for inference: https://github.com/youkaichao/dolly/blob/master/generate.py . It seems this model is only optimized for instruction following rather than chatting.

**Comment by srowen** [comment]
This isn't a converstaional model, it's text-generation / instruction-following model, like Alpaca, GPT-J, etc. You can ask it questions but it is not set up as a chat model

**Comment by yinwangsong** [comment]
> @yinwangsong I write a script for inference: https://github.com/youkaichao/dolly/blob/master/generate.py . It seems this model is only optimized for instruction following rather than chatting.

Thanks a lot :)

**Comment by yinwangsong** [comment]
> This isn't a converstaional model, it's text-generation / instruction-following model, like Alpaca, GPT-J, etc. You can ask it questions but it is not set up as a chat model

All right... Another question: what should I do to export the weights trained in databricks to my local pc? I am not familar with databricks :(

**Comment by yinwangsong** [comment]
> This isn't a converstaional model, it's text-generation / instruction-following model, like Alpaca, GPT-J, etc. You can ask it questions but it is not set up as a chat model

All right... Another question: what should I do to export the weights trained in databricks to my local pc? I am not familar with databricks :(

**Comment by yinwangsong** [comment]
> This isn't a converstaional model, it's text-generation / instruction-following model, like Alpaca, GPT-J, etc. You can ask it questions but it is not set up as a chat model

All right... Another question: what should I do to export the weights trained in databricks to my local pc? I am not familar with databricks :(

**Comment by srowen** [comment]
They're just on S3 (if you're in AWS, for example). But probably the simplest thing is to install the `databricks` CLI from pypi and then `databricks fs cp dbfs:/.../weights/ .`

**Comment by yinwangsong** [comment]
> They're just on S3 (if you're in AWS, for example). But probably the simplest thing is to install the `databricks` CLI from pypi and then `databricks fs cp dbfs:/.../weights/ .`

Great! Thanks a lot :)

**Comment by yinwangsong** [comment]
> 

I finetuned on 8 V100 GPUs with FP16 acceleration for about 1.5h (1 epoch) on databricks.
