### ISSUE TITLE
JSONDecodeError on running dolly repo with review dataset.

### ISSUE THREAD

**Issue by dineshreddy221** [databrickslabs/dolly#161]
Hi,

Started running dolly repo in my workspace repo, i prepared a custom dataset with classification task of 6k records. When i am running the deepspeed code in repo, i am ending up with json decoder error and this error is repeating when i am using another dataset also on the same line mentioned in below output.

Output of deepspeed code:
<img width="949" alt="error_json_decoder1" src="https://github.com/databrickslabs/dolly/assets/90762347/d086bfd9-3f9d-4ea5-9ffd-e4074e12b8dd">

<img width="952" alt="error_json_decoder2" src="https://github.com/databrickslabs/dolly/assets/90762347/2a04ed2c-06be-4807-864f-8d23bac5cec1">

<img width="959" alt="error_json_decoder3" src="https://github.com/databrickslabs/dolly/assets/90762347/74538afa-f456-4ff7-b44d-d5ebfbebeae6">

<img width="957" alt="error_json_decoder4" src="https://github.com/databrickslabs/dolly/assets/90762347/268384a4-c8d0-495b-baf8-1c51cd51b74f">

deepspeed code:
<img width="517" alt="deepspeed_coed" src="https://github.com/databrickslabs/dolly/assets/90762347/1d0887a9-20eb-4ae3-ab45-e84a73f99826">

deepspeed config:
{
    "bf16": {
      "enabled": "auto"
    },
    "optimizer": {
      "type": "AdamW",
      "params": {
        "lr": "auto",
        "betas": "auto",
        "eps": "auto",
        "weight_decay": "auto"
      }
    },
    "scheduler": {
      "type": "WarmupLR",
      "params": {
        "warmup_min_lr": "auto",
        "warmup_max_lr": "auto",
        "warmup_num_steps": "auto"
      }
    },
    "zero_optimization": {
      "stage": 2,
      "offload_optimizer": {
         "device": "cpu",
         "pin_memory": true
      },
      "overlap_comm": true,
      "contiguous_gradients": true,
      "sub_group_size": 1e9,
      "reduce_bucket_size": "auto",
      "stage3_prefetch_bucket_size": "auto",
      "stage3_param_persistence_threshold": "auto",
      "stage3_max_live_parameters": 1e9,
      "stage3_max_reuse_distance": 1e9,
      "stage3_gather_16bit_weights_on_model_save": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",  
    "wall_clock_breakdown": false
  }

Databricks Cluster configurations:
12.2 LTS ML runtime.
Standard_NC8as_T4_v3 - 56 GB memory 1 GPU.

Issue:
I am facing the problem when running deepspeed code, it is throwing json decoder error on line 25 for another data also.
please let me know what is my issue and how can figure it out.

Thank you in advance.

**Comment by srowen** [comment]
It pretty much tells you the error. You have a syntax error in your deepspeed JSON config. I don't immediately see a problem there, but double check your actual config file is valid around that line.

**Comment by dineshreddy221** [comment]
Thank you @srowen it worked for me.
