### ISSUE TITLE
Invoking deepspeed with HF token converts flags to literal values

### ISSUE THREAD

**Issue by opyate** [databrickslabs/dolly#165]
I've modified the CLI in [this script](https://github.com/databrickslabs/dolly/blob/master/training/trainer.py) to accept a repo and an HF token, so I can push to the hub from the script. (I'm integrating PEFT, so the resulting artefacts are a bit different.)

However, it seems as though the token is masked, but it breaks the CLI, as the `{foo}` flags are passed literally, and the dollar-values are completely omitted.

This is the command in the notebook I modified (note the two extra params at the end):

```
!deepspeed {num_gpus_flag} \
    --module training.trainer \
    --input-model {input_model} \
    --deepspeed {deepspeed_config} \
    --epochs $epochs \
    --local-output-dir {local_output_dir} \
    --dbfs-output-dir {dbfs_output_dir} \
    --per-device-train-batch-size $batch_size \
    --per-device-eval-batch-size $batch_size \
    --logging-steps 10 \
    --save-steps 200 \
    --save-total-limit 20 \
    --eval-steps 50 \
    --warmup-steps 50 \
    --test-size 100 \
    --lr $lr \
    --repo-name $repo_name \
    --hf_token $huggingface_token
```

Here's a clue from the log that those bracketed values are passed literally:

> /local_disk0/.ephemeral_nfs/envs/pythonEnv-437fc41d-a20b-4579-bf72-9fbfcb02b73f/bin/python: can't open file '/Workspace/Repos/opyate@gmail.com/dolly/{num_gpus_flag}': [Errno 2] No such file or directory

This issue continues the discussion in #158

**Comment by opyate** [comment]
> Is `num_gpus_flag` actually set in your modification?

Yes. The command stops working when I add `--hf_token $huggingface_token`.

**Comment by srowen** [comment]
Yeah should both work. It really seems like num_gpus_flag isn't set. Can you print it in Python above this command to be sure?

**Comment by opyate** [comment]
![image](https://github.com/databrickslabs/dolly/assets/96808/cf28f7c2-f9a6-49d4-8345-21f204bbf11f)

I'm trying to recreate this in a new notebook.

**Comment by opyate** [comment]
![image](https://github.com/databrickslabs/dolly/assets/96808/c24557b6-7152-405c-a7b5-71ad2a96dbdb)

**Comment by opyate** [comment]
Also from faulty notebook, just to show the token works:
![image](https://github.com/databrickslabs/dolly/assets/96808/f4539b9d-0591-4b1e-aecc-7e125d012cb6)

**Comment by opyate** [comment]
Ah, I found the issue. 

After the above code where I set the token, I do a pip install, which does:

> Python interpreter will be restarted.

...which wipes the token variable.

So sorry to have wasted your time with this! Thanks for your help, as always :)

**Comment by opyate** [comment]
I've added this as an idea here for developer experience: https://ideas.databricks.com/ideas/DBE-I-1116

**Comment by srowen** [comment]
Are you using the latest runtime? it does not restart the python interpreter - leaves it up to you. If that's the idea, it is done already

**Comment by opyate** [comment]
> Are you using the latest runtime? it does not restart the python interpreter - leaves it up to you. If that's the idea, it is done already

Thanks for the tip - I'll look into getting interpreter restart disabled.
