### ISSUE TITLE
How many epochs do you train to achieve the performance in the blog?

### ISSUE THREAD

**Issue by youkaichao** [databrickslabs/dolly#17]
Hi, team, the [blog](https://www.databricks.com/blog/2023/03/24/hello-dolly-democratizing-magic-chatgpt-open-models.html) is exciting, but I want to know how many epochs do you train to achieve the performance in the blog?

I trained the model for one epoch, and use the generate script [here](https://github.com/youkaichao/dolly/blob/master/generate.py), but the result I get is not very satisfying: (prompt template from Alpaca, and the blue part is the model's response).

![image](https://user-images.githubusercontent.com/23236638/227849366-112343d6-a0a6-4142-8da7-278d87a3954e.png)

**Comment by asfires** [comment]
Have you tried experimenting with different hyperparameter values in your generate.py script? For instance, your temperature appears to be extremely high (1.0), which might explain why you’re getting such a goofy response here.

**Comment by maziyarpanahi** [comment]
I am also interested in how to evaluate the fine-tuned model. Obviously, eye-balling the results is not a solid option. (I will leave it for 2 Epochs tonight, but I have no idea if it is fitting further or overfitting.)

**Comment by srowen** [comment]
1 epoch: https://github.com/databrickslabs/dolly/blob/master/train_dolly.py#L109
You can indeed train longer or adjust hyperparams as you like.

I know the folks working on this also observed similar issues, and it's related to how it's prompted. Maybe they can weigh in with what's been working better - I believe it relates to the `###` making it overly keen on things like hashtags in the result :)

**Comment by youkaichao** [comment]
@srowen Can you kindly share the prompt and hyper-parameters you use to reproduce the results in the blog?

**Comment by srowen** [comment]
Paging @matthayes et al, that I do not know

**Comment by yinwangsong** [comment]
> @srowen Can you kindly share the prompt and hyper-parameters you use to reproduce the results in the blog?

Maybe you just ask your question directly to the model without any prompt template？

**Comment by matthayes** [comment]
1 epoch should be sufficient to get pretty good results.  I've opened #27 which should generate responses similar in quality as the blog post given the code that is checked into this repo.

**Comment by maziyarpanahi** [comment]
Thanks @matthayes 
The results are now much better with this `generate`:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/5762953/228160718-452452db-e9de-4ed7-935d-96a3577411c4.png">
