### ISSUE TITLE
training: CUDA out of memory

### ISSUE THREAD

**Issue by vincentvic** [databrickslabs/dolly#170]
Hi,

I'am using a virtual machine Série NCsv3 (Standard_NC24s_v3 448GB Memory with 4 GPU) but during the phase of training, I have an error about memory cuda " CUDA out of memory. Tried to allocate 2.59 GiB (GPU 3; 15.78 GiB total capacity; 10.49 GiB already allocated; 1.73 GiB free; 13.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

The config is as follows:
 - input_model: EleutherAI/pythia-2.8b
 - per-device-train-batcg-size: 3
 - per device-eval-batch-size: 3
 - And I modified the config as it has been recommended 
 
Do you know why I have this error ? Thank you

**Comment by srowen** [comment]
What is your training data? Generally, you will have to further change the settings as needed. You can turn down batch size for example. This isn't specific to this model, just generally what you have to do with deepspeed on your own

**Comment by srowen** [comment]
Also, did you set parameter offload? you are on 16GB, not 32GB V100s, and that is not what the suggestions cover. You need to make further changes like param offload.
