### ISSUE TITLE
Clarification on GPU Accelerated compute

### ISSUE THREAD

**Issue by dineshreddy221** [databrickslabs/dolly#172]
Hi,

If i go with NCasT4_v3-series of bigger GPU, vCPU and memory, can I be able to run the 2.8b param model.

<img width="454" alt="image" src="https://github.com/databrickslabs/dolly/assets/90762347/9b23e6ab-7103-4e50-badd-79e95193ec7d">

Is GPU memory 16GiB works or need to go more than that?

please let me know, I am confusion on this configuration to use.

**Comment by srowen** [comment]
T4 has 16GB of GPU mem. That should be plenty to load the 2.8B param model in 16-bit (5.6GB GPU mem). This is not specific to this model.
