### ISSUE TITLE
Using dolly-v2-7b and generating 5000k words I get this error: The size of tensor a (2048) must match the size of tensor b (2049) at non-singleton dimension 3

### ISSUE THREAD

**Issue by zubair-ahmed-ai** [databrickslabs/dolly#174]
I need to be able to generate a long document, this is my first time, I am using Langchain for this, I noticed that using dolly-v2-3b it was repeating the same text 3-4 times. so I used dolly-v2-7b instead but I ran into the above error. 

[I read you should chunk your generations so perhaps it applies here also](https://github.com/huggingface/transformers/issues/4542#issuecomment-633280592) but 
* I am not sure how to generate in chunks?
* how to get rid of this error?
* would reducing the generation to 2500 words work?
* what's the best strategy to achieve this?

**Comment by srowen** [comment]
You're exceeding the model's token window size. Whatever you are doing with langchain (turn on verbose=True to see) ends up feeding too much. Not sure what you are doing so hard to say what to do

**Comment by zubair-ahmed-ai** [comment]
@srowen Thanks for replying, I am trying to do [this as described in this issue](https://github.com/hwchase17/langchain/issues/4866). I noticed that I already had `verbose=True` on [SequentialChain](https://python.langchain.com/en/latest/modules/chains/generic/sequential_chains.html#sequential-chains) in Langchain but not in [LLMChains](https://python.langchain.com/en/latest/modules/chains/generic/llm_chain.html#llm-chain) so trying that now to see if anything changes.

How to set the right token window size on this model?

**Comment by srowen** [comment]
You can't change the window size. This is a usage error. It's not a problem with langchain or this model.

**Comment by srowen** [comment]
It's 2048

**Comment by opyate** [comment]
I also saw this today with a short prompt (and no LangChain):

![image](https://github.com/databrickslabs/dolly/assets/96808/ee9fdab7-cccb-4c58-b304-f6abdcb25f4b)

**Comment by srowen** [comment]
The input context window affects the max length too, as the generation output is fed back to generate more tokens. At a max of 2048, you're going to run off the end because of your prompt (as well as prompting in the pipeline). max of 2048 won't work if it keeps generating that long.

**Comment by srowen** [comment]
Do you really need long generation? I'm just making sure you're setting what you think you are.
I'd imagine something like 1900 or so is safe.

**Comment by opyate** [comment]
> Do you really need long generation?

For our current experiment, yes. I'm converting doc content to JSON, and the doc can be quite large, hence the generated JSON can be quite large.

**Comment by zubair-ahmed-ai** [comment]
I need long generations too @srowen as well as long context

**Comment by srowen** [comment]
If you need more context window than this model provides, then use another model (MPT Instruct for example). Or reassess whether you really usefully can use that much context and look at ways to use the LLM iteratively.
