### ISSUE TITLE
General Rule of Thumb when Estimating GPU Memory Requirements

### ISSUE THREAD

**Issue by Hegelim** [databrickslabs/dolly#176]
What's the general rule of thumb when it comes to estimating how much GPU memory I would need?
1. In terms of training?
2. In terms of fine-tuning?
3. In terms of inferencing?

And how would the rough estimate of 2x number of parameters fit in here? Does it refer to simply loading the model?

**Comment by srowen** [comment]
Pre-training is not recommended. This is the kind of thing that can cost a million bucks.
Fine-tuning could be fine. I'm saying the task is the same, so hardware considerations are the same.

Fine-tuning is just fairly different. It will in general need more memory. It also offers more possibilities to trade off mem for speed as you can afford latency. See: deepspeed

The answer depends on the model, your input, and how you train. the answer is quite different for 3B vs 12B here, even. I would tell you, as above and in the README, that A100s are ideal for training (40GB). Anything else will require tradeoffs to work that will cost more and take a lot longer. This is for fine-tuning. You could expect to spend thousands of dollars, probably, if that helps. Not $100 and not $10000, probably.
