### ISSUE TITLE
generate_response with context

### ISSUE THREAD

**Issue by ebilal** [databrickslabs/dolly#177]
Hi - How should I format the instruction for generate_response if I have context.
Would this work?
`template = "{instruction}\n\nInput:\n{context}"`
`model_input = template.format(instruction='some instruction', context='some context')`
`response = get_response(model_input)`

**Comment by srowen** [comment]
Depends on what you are trying to do, and how you are loading the model, so hard to say.
If you are using pipeline() to load, then it already puts a prompt around your input. If you want to supply context and instruction, then I have typically tried {context} followed by {instruction}, but you can try both ways. If you use pipeline() then no other boilerplate should be needed, but, again, depends on what you are doing here, there is no one way to prompt a model for all tasks!
