### ISSUE TITLE
Dolly Model Register on Mflow and Serve using Databricks Model Serving

### ISSUE THREAD

**Issue by SrikarPrayaga06** [databrickslabs/dolly#191]
I am trying to register the dolly model on mlflow and serve it using the databricks model serving. The serving container keeps failing and endpoint is unable to be created.

**Comment by srowen** [comment]
You won't be able to run this in Databricks serving unless you are opted into the GPU serving private preview. The preview should let you serve the 7B model. (This is a Databricks question so I'll close it here)
