### ISSUE TITLE
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 's3://skillsai-llms/dolly_LLM/dolly-7b-cust_trained_v5'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by deepakkrish91** [databrickslabs/dolly#198]
Hi fine tuned dolly-v2-7b using PEFT and LoRa method in databricks. I was able to store the custom model in dbfs and invoke the same for inference. But when I migrated the same model to S3 bucket to use it in aws, getting an error while invoking - Though the model repo has all dependent files and the path is also correct, not able to invoke the model using the below command.

######## Load peft config for pre-trained checkpoint etc. 
peft_model_id = "s3://skillsai-llms/dolly_LLM/dolly-7b-cust_trained_v5"
config = PeftConfig.from_pretrained(peft_model_id) 

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 's3://skillsai-llms/dolly_LLM/dolly-7b-cust_trained_v5'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-29-746d21b45842> in <module>
      1 # Load peft config for pre-trained checkpoint etc.
      2 peft_model_id = "s3://skillsai-llms/dolly_LLM/dolly-7b-cust_trained_v5"
----> 3 config = PeftConfig.from_pretrained(peft_model_id)

/opt/conda/lib/python3.7/site-packages/peft/utils/config.py in from_pretrained(cls, pretrained_model_name_or_path, subfolder, **kwargs)
    112                 )
    113             except Exception:
--> 114                 raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")
    115 
    116         loaded_attributes = cls.from_json_file(config_file)

ValueError: Can't find 'adapter_config.json' at 's3://skillsai-llms/dolly_LLM/dolly-7b-cust_trained_v5'

**Comment by srowen** [comment]
I don't think an s3 URI works here. But this is a question about HF or PEFT, not this model
