### ISSUE TITLE
Facing error while training on custom data using deepspeed

### ISSUE THREAD

**Issue by kapilmayank** [databrickslabs/dolly#199]
While training I am getting this error
Runtime error:Error building extension 'cpu admin'
then Attribute error 'DeepSpeedCPUADAM' has no attribute 'ds_opt_adam'
I have used FP16 instead of bf16 because it required torch>=1.10 using Ampere GPU with cuda>=11.0

Please help me with this

**Comment by kapilmayank** [comment]
@srowen  ,please help

**Comment by srowen** [comment]
This means you are missing some CUDA libraries usually, like cusparse. This is not the original error. The provided training script shows installing these. Please search existing issues first and follow the provided script
