### ISSUE TITLE
LLM to analyze DataFrame

### ISSUE THREAD

**Issue by seshsan** [databrickslabs/dolly#204]
I am trying to use LLM-like approach to perform a literature survey. The idea is to make the algorithm study a long list of search result(a text file with all the key parameters such as authors, abstract etc.) and then answering to a number of well- formulated questions… Sounds quite easy but valuable. I first used the “langchain” example code with only one reference text as “context”, using the: 
“llm_context_chain = LLMChain(llm=hf_pipeline, prompt=prompt_with_context)
…… 
response = llm_context_chain.predict(instruction=instruction, context=context)”
and tried different questions(instructions) about the content etc. with excellent results.

The next step in my mind was to replace the context with content of my search file- in dataframe format. I started to get a portion of the search result(only 100 of them) in an xml file to then convert it to a dataframe. I expected that LLmchain can do the job.
After some searching I ended up using the “agent”:
“agent = create_pandas_dataframe_agent(llm= hf_pipeline df=df2, verbose=True)
agent.run("Could you please summarize how machine learning has been used in the abstracts ")”

But no matter if I use “OpenAI(temperature=0)” or “hf_pipeline”, neither changing the “question”,  I either receive the error: “'Agent stopped due to iteration limit or time limit.'” or something about the “Action: python_repl_ast” not being suitable for the task… 

It handles simple queries (such as, "How many and which articles contain machine learning", but it cannot provide any type of analysis/ summary of the context…

I don’t know what I could use instead of this “agent”, that would be capable for the task.
One can perhaps conclude that I should give up using the already trained models, and try to train my own on the dataset…

I would appreciate “any” suggestion/proposal to solving the problem

**Comment by srowen** [comment]
I don't think this is a question about training Dolly?
