### ISSUE TITLE
Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0

### ISSUE THREAD

**Issue by aero-girl** [databrickslabs/dolly#24]
Hey 👋🏽,

I am not able to see the Standard_ND96asr_v4 that has been recommended.
I am on Azure and location: West Europe, and the `Standard_ND96asr_v4` is not available in West Europe region.

However, I managed to get a `Standard_NC24s_v3` (448GB, 4GPUs) - see screenshot below. (By the way this wasn't an easy process as well, took me many attempts to get Azure to increase the quota)
![image](https://user-images.githubusercontent.com/5180795/228061707-d98808fd-2131-437f-8660-e7fa6b5aa48f.png)

However...
Upon training dolly, I get the following error:
ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0

I am assuming it's because of the type of GPU selected to train dolly. 
Is there an alternative GPU that would work, other than the `Standard_ND96asr_v4`? Is there a workaround that someone has come across?

**Comment by asfires** [comment]
See: https://azureprice.net/compare?vms=Standard_NC24rs_v3,Standard_ND96asr_v4
https://learn.microsoft.com/en-us/azure/virtual-machines/nda100-v4-series
https://learn.microsoft.com/en-us/azure/virtual-machines/ncv3-series

Looks like Standard_NC24rs_v3 doesn't support training and inference scenarios for deep learning and that it's geared more toward high-performance computing. You may have better luck with something else in the ND series if Standard_ND96asr_v4 specifically isn't available for you.
