### ISSUE TITLE
create a official huggingface model?

### ISSUE THREAD

**Issue by loklok-infi** [databrickslabs/dolly#26]
I found some dolly related models on huggingface's website, but not sure if they are the official version. Any plan to create one on huggingface? Maybe people could test the performance of dolly easier in that case.

**Comment by srowen** [comment]
See https://github.com/databrickslabs/dolly/issues/3#issuecomment-1483701513 - because of the non-commercial restrictions on source data, at the moment, not distributing publicly to not accidentally encourage commercial use. But as you say, people have already done it anyway.
