### ISSUE TITLE
Finding instances for new nodes, acquiring more instances if necessary

### ISSUE THREAD

**Issue by pockywei** [databrickslabs/dolly#29]
I have try Azure databricks, but with standard_ND96 GPU to create a cluster, always showed "Finding instances for new nodes, acquiring more instances if necessary"?  Is this always happen?

**Comment by srowen** [comment]
This typically means the instance type is not easily available in your region. It may take more time to provision, or fail. If it's going to work, it should be well within 10 minutes. The A100 instances are highly in demand. It's possible to train on an A10 or V100 instance too, and I was going to post small changes that enable it.
