### ISSUE TITLE
Downloading the model and performing inference only

### ISSUE THREAD

**Issue by mycaule** [databrickslabs/dolly#34]
Is there an easy way to download the model generated by Databricks in the blog post, instead of retraining?
In fact, for a number of reasons, it still might not be so easy to retrain (access to Databricks, or to `Standard_ND96asr_v4` instance).

Also, what is the recommended instance type for inference only, _ie._ calling the `generate_response` function?

Thank you very much for the hard work.

**Comment by mycaule** [comment]
wrote an email to support.

see #3

**Comment by matthayes** [comment]
We’ve released the model here: https://huggingface.co/databricks/dolly-v1-6b
