### ISSUE TITLE
problem when setting training environment

### ISSUE THREAD

**Issue by 545999961** [databrickslabs/dolly#41]
In training step 2, when I select Databricks Runtime '12.2 LTS ML (includes Apache Spark 3.3.2, GPU, Scala 2.12)', I find that I can't select 'Standard_ND96asr_v4', the best choice is 'Standard_NC64as_T4_v3', can I use cluster whith this configuration? Thanks for your help.

**Comment by srowen** [comment]
I am guessing that the ND96 is not available in the region you're in?

The T4 instances are probably not enough for this model. It might work if you make the modifications described in https://github.com/databrickslabs/dolly#training-on-other-instances

But, better still is to use one of the A10 (or V100) instance types described there.

**Comment by 545999961** [comment]
ok.
Thanks for your help.
