### ISSUE TITLE
problem when start cluster

### ISSUE THREAD

**Issue by 545999961** [databrickslabs/dolly#42]
when start a cluster, I account the problem as follow:
Unexpected startup failure: An unexpected error occurred while setting up the cluster. If the problem persists, please try again and contact Databricks.
How can I solve this problem? Thanks for your help.

**Comment by 545999961** [comment]
The detail information is:
Unable to add 1 container to the cluster. Will attempt to retry: false. Reason: Unexpected startup failure

**Comment by srowen** [comment]
You probably don't have quota with the cloud provider. Click the "Event Logs" for the cluster and click the failure to see details.

**Comment by 545999961** [comment]
It says that 'ADD_NODES_FAILED: Unable to add 1 container to the cluster. Will attempt to retry: false. Reason: Unexpected startup failure. Internal error message: Timeout while placing nodes.' Does it mean that I don't have quota with the cloud provider? Thanks for your help.

**Comment by srowen** [comment]
Hm. That could mean that it wasn't able to provision the node. That isn't a quota problem, I believe. Can you try again?
