### ISSUE TITLE
new error on "device_map" parameter in the model

### ISSUE THREAD

**Issue by lillian521** [databrickslabs/dolly#46]
Hi,
after I installed accelerate and re-run the model, new error like below shows, I tried installed the safetensors and re-started the kernel but still had the same error msg. Please kindly advise how to fix. Thanks.
"
The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for 
them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in 
this format."

**Comment by emattia** [comment]
In the `generate.py` file's `load_model_tokenizer_for_generate`, adding `offload_folder` argument worked for me in the same situation:
```
AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path, offload_folder=<FOLDER OF YOUR CHOICE>, ...)
```
