### ISSUE TITLE
Unable to log custom model on top of databricks/dolly-v1-6b on databricks model registery ?

### ISSUE THREAD

**Issue by msinha251** [databrickslabs/dolly#47]
Hi Team, 

I am trying to train databricks/dolly-v1-6b on custom dataset on databricks enterprise account. I am able to train the model but unfortunately I am unable to log or register the model on Model Registry so that i can use it with model serving. 

Does any one have tried or any option or availability for this ?

**Comment by msinha251** [comment]
Yeah it's bit large (12 gb).

I am trying to log it with `mlflow.log_artifacts(model_path)`

error:  `EntityTooLargeYour proposed upload exceeds the maximum allowed size`

**Comment by srowen** [comment]
Yeah, that's an MLflow and/or Databricks and/or S3 limitation right now (5GB max I think), but I know people are working on it for just this reason. This is more an MLflow issue rather than related to the training script here, but yes.
