### ISSUE TITLE
OOM while training (7xx step) on 4x A100 40GB

### ISSUE THREAD

**Issue by hyn2028** [databrickslabs/dolly#48]
I am trying to train on a `4x A100 40GB` system. None of the settings were changed from the default except for the `--num_gpus 4` option. 

It seems to be working really well, but suddenly `CUDA OOM` occurs during the 7xxth step. It was obviously not the step that was doing the evaluation or saving the model. 

Is this possible? Is it because I didn't use 8 gpus? Does increasing the number of GPUs reduce the VRAM usage of each GPU?

**Comment by srowen** [comment]
Hm, I wouldn't have thought it would OOM if you use the same per-device batch size, but it's possible that some deepspeed magic works better on 8 GPUs. That said, GPU mem utilization on 8 has plenty of headroom. Is this reproducible? You can try the settings in the README that help it run in less mem, but I wouldn't expect this on A100s.

**Comment by hyn2028** [comment]
On my system this was completely reproducible. OOM occurs at the same step.

There was really no headroom of VRAM in my system. Less than 500MB was left for the GPU that uses the most memory.

Do you have any idea how much headroom is left if you use 8 of them? There is something I saw in the issue, but it seems to have used 55GB because it was an 80GB model.

**Comment by srowen** [comment]
I recall the GPUs were at about 70% mem. This should be on 40GB A100s not 80GB.

**Comment by hyn2028** [comment]
Then I was using 98% of my VRAM, so I'm guessing that the low memory margin was due to the low number of GPUs. I haven't tested this, but it's helpful. Thank you very much.
