### ISSUE TITLE
Python kernel is unresponsive due to Py4JSecurityException

### ISSUE THREAD

**Issue by iris-engineering-data** [databrickslabs/dolly#49]
I tried running 

```
import numpy as np
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    PreTrainedModel,
    PreTrainedTokenizer
)
 
tokenizer = AutoTokenizer.from_pretrained("databricks/dolly-v1-6b", padding_side="left")
model = AutoModelForCausalLM.from_pretrained("databricks/dolly-v1-6b", device_map="auto", trust_remote_code=True, offload_folder="offload")
```

with this cluster configuration

> Driver: m5d.large · Workers: m5d.large · 1-2 workers · Spot · fall back to On-demand · 12.2 LTS (includes Apache Spark 3.3.2, Scala 2.12) · us-east-1b

However, after 5 minutes of running, it throws this error

> Fatal error: The Python kernel is unresponsive.
> ---------------------------------------------------------------------------
> The Python process exited with an unknown exit code.
> 
> The last 10 KB of the process's stderr and stdout can be found below. See driver logs for full logs.
> ---------------------------------------------------------------------------
> Last messages on stderr:
> Wed Apr  5 13:52:47 2023 Connection to spark from PID  2437
> Wed Apr  5 13:52:47 2023 Initialized gateway on port 41767
> Wed Apr  5 13:52:47 2023 Connected to spark.
> Unexpected internal error while setting REPL context in `pre_command_execute`: An error occurred while calling o402.tags. Trace:
> py4j.security.Py4JSecurityException: Method public scala.collection.immutable.Map com.databricks.backend.common.rpc.CommandContext.tags() is not whitelisted on class class com.databricks.backend.common.rpc.CommandContext
> 	at py4j.security.WhitelistingPy4JSecurityManager.checkCall(WhitelistingPy4JSecurityManager.java:473)
> 	at py4j.Gateway.invoke(Gateway.java:305)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
> 	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
> 	at java.lang.Thread.run(Thread.java:750)

Are there special steps done to overcome this? Seems like it's not happy with the hugging face's method?

Thanks,

**Comment by srowen** [comment]
I think that's an ugly way of saying "out of memory"
Your cluster config is all wrong though. You have a tiny driver - 2 cores, 8GB RAM, no GPUs! and you have 2 workers doing nothing. That won't work at all. You want 8 x A100 GPU instances. Please see https://github.com/databrickslabs/dolly#getting-started-with-training
