### ISSUE TITLE
RuntimeError: Expected only a single token for '### Response: ' but found [50402, 198]

### ISSUE THREAD

**Issue by junhua-wu** [databrickslabs/dolly#51]
The issue:
Got a runtime error at line 87 of training/generate.py:
 response_key_token_id = get_special_token_id(tokenizer, RESPONSE_KEY_NL)

The message:
RuntimeError: Expected only a single token for '### Response:
' but found [50402, 198]

The possible reason:
As RESPONSE_KEY_NL = f"### Response:\n"
tokenizer.encode(RESPONSE_KEY_NL) returns 2 tokens, hence the runtime error

**Comment by lavarith** [comment]
I ran into a similar issue. They updated the token types in the code. If you used a model trained on the old version, the newer code didn't work. Revert the code to a few versions ago.

**Comment by hax4usincupad** [comment]
same issue. any updates ?

**Comment by matthayes** [comment]
V2 training code was added in #88, and along with this change I improved generation to work with the different variations of the model tokenizers.

**Comment by matthayes** [comment]
Closing this as I believe it is now fixed.  Please reopen if there are still issues.
