### ISSUE TITLE
How long does it take to train?

### ISSUE THREAD

**Issue by logchan** [databrickslabs/dolly#6]
Trying to estimate the cost of using 8 A100's :)

**Comment by matthayes** [comment]
I’ve been able to train it in a little under 30 minutes, not including the time to download the input model.

**Comment by jcsjacekj** [comment]
> I’ve been able to train it in a little under 30 minutes, not including the time to download the input model.

On what machine? VM - what size?

**Comment by srowen** [comment]
I believe Matt et al are using 8 x A100 40G VMs - `p4dn.24xlarge` or `Standard_ND96asr_v4`. This is on the front-page README, FWIW.

**Comment by matthayes** [comment]
Sorry I meant that using 8 A100s I was able to train in under 30 minutes.  This was on a single Standard_ND96asr_v4 as @srowen mentioned.

**Comment by logchan** [comment]
Thanks for your input!

**Comment by opyate** [comment]
Using [g5.12xlarge](https://aws.amazon.com/ec2/instance-types/g5/) (4 x A10G) and the [adjusted config](https://github.com/databrickslabs/dolly#a10-gpus-1), the 3b model takes 5.6 hours.
