### ISSUE TITLE
Can't load the model and run the inference example

### ISSUE THREAD

**Issue by jpzhangvincent** [databrickslabs/dolly#62]
<img width="1519" alt="Screenshot 2023-04-12 at 2 56 29 PM" src="https://user-images.githubusercontent.com/7220686/231594810-31aa646c-7257-46f7-813c-171f4d56a4a0.png">

**Comment by srowen** [comment]
Hm, that line works for me. What version of `transformers` do you have?
(I think there's a different issue with this `pipeline` impl that I'm investigating, but I don't think it's related)

**Comment by jpzhangvincent** [comment]
I installed the version - 4.25.1 from the `requirements.txt` from the `train_dolly.py` and ran in the `12.2 LTS ML` Databricks notebook environment.

**Comment by jpzhangvincent** [comment]
Another side question, if we use the 12.2 LTS ML runtime and choose a GPU instance, do we have to run the following to install the cuda packages, or it's already pre-installed? 
```shell
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcusparse-dev-11-3_11.5.0.58-1_amd64.deb -O /tmp/libcusparse-dev-11-3_11.5.0.58-1_amd64.deb && \
  wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcublas-dev-11-3_11.5.1.109-1_amd64.deb -O /tmp/libcublas-dev-11-3_11.5.1.109-1_amd64.deb && \
  wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcusolver-dev-11-3_11.1.2.109-1_amd64.deb -O /tmp/libcusolver-dev-11-3_11.1.2.109-1_amd64.deb && \
  wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcurand-dev-11-3_10.2.4.109-1_amd64.deb -O /tmp/libcurand-dev-11-3_10.2.4.109-1_amd64.deb && \
  dpkg -i /tmp/libcusparse-dev-11-3_11.5.0.58-1_amd64.deb && \
  dpkg -i /tmp/libcublas-dev-11-3_11.5.1.109-1_amd64.deb && \
  dpkg -i /tmp/libcusolver-dev-11-3_11.1.2.109-1_amd64.deb && \
  dpkg -i /tmp/libcurand-dev-11-3_10.2.4.109-1_amd64.deb
```

**Comment by srowen** [comment]
You have to install those. I think the error you're hitting is the same as this one, and I might know why: https://github.com/databrickslabs/dolly/issues/60

**Comment by srowen** [comment]
Could you check if adding `task="text-generation"` to your `pipeline()` call makes it work?

**Comment by srowen** [comment]
What hardware?

**Comment by markusantonuis** [comment]
> What hardware?
core i5 4790k (clocked to 4.4ghz), gtx970 (4gb), 16Gb. I'm not interested in speedy responses but do acknowledge my hardware is quite old

**Comment by srowen** [comment]
That isn't even enough mem to load the model in the CPU. You need a GPU really. These are 12b param models!

**Comment by markusantonuis** [comment]
Fair enough, do you think i could load one of the smaller models? I would just like some basic language generation to query a dataset that I have. I expected it to be quite slow, but didn't think it would outright reject the hardware.

**Comment by srowen** [comment]
Try the 3B param model: https://huggingface.co/databricks/dolly-v2-3b
That won't fit on your GPU either so will offload onto CPU.
It's going to be very slow to generate a result.
