### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by qmister** [databrickslabs/dolly#63]
operating system：Windows 10 专业版
python version :  Python 3.10.11

When I just want pip3 install - r requirements_ Dev.txt will appear
 Using cached https://mirrors.aliyun.com/pypi/packages/0d/6a/216004220f0658ac4ee2c06f724b1557d1a5f0533f7fd0830845351d0b30/deepspeed-0.8.0.tar.gz (749 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-b9_i45kc\deepspeed_212e4e5c59c94e27afa26375d642bd71\setup.py", line 122, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by srowen** [comment]
Do you otherwise have pytorch installed? we may need to add it to the dependencies for people working in a blank env, if that resolves it.

**Comment by AngelTs** [comment]
Same error, pytorch is installed

**Comment by srowen** [comment]
What version? Try the latest requirements.txt
