### ISSUE TITLE
RuntimeError: Placeholder storage has not been allocated on MPS device!

### ISSUE THREAD

**Issue by LeiHao0** [databrickslabs/dolly#67]
Env:
```
macOS== 13.3.1
M1Max, 64G
python==3.10.10
tensorflow-macos==2.12.0  
tensorflow-metal==0.8.0
```

It can run on Apple Silicon with CPU, but when I try to set the device to `mps` instead of  `cuda` or `cpu`

```
device = torch.device("mps")
generate_text = InstructionTextGenerationPipeline(model=model, tokenizer=tokenizer, device=device)
generate_text.model.to(device)
```

It shows these error msg.

```
miniconda/envs/dolly/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Placeholder storage has not been allocated on MPS device!
```

I think it seems another model hasn't been set to `mps` correctly, but I cannot find which model raised this error.

**Comment by srowen** [comment]
I think that's not really something in scope for this project, and this doesn't seem related to Dolly directly. Maybe someone has an idea; we can leave open for a bit. 
I doubt anyone's going to be happy with this on CPUs

**Comment by appenz** [comment]
I am running into exactly the same problem. device_map="auto" maps the model to the CPU. Manually setting it to Apple's mps silicon creates this error.
