### ISSUE TITLE
How to make dolly run with gradio interface?

### ISSUE THREAD

**Issue by FurkanGozukara** [databrickslabs/dolly#68]
Downloaded all files here:

![image](https://user-images.githubusercontent.com/19240467/231809199-3bfb8102-cec0-4f28-89e9-dc596b09a928.png)

Using this ipynb notebook

```
import gradio as gr
from transformers import pipeline
import torch

theme = gr.themes.Monochrome(
    primary_hue="indigo",
    secondary_hue="blue",
    neutral_hue="slate",
    radius_size=gr.themes.sizes.radius_sm,
    font=[gr.themes.GoogleFont("Open Sans"), "ui-sans-serif", "system-ui", "sans-serif"],
)

instruct_pipeline = pipeline(model="F:/Dolly 2.0/dolly-v2-12b", torch_dtype=torch.bfloat16, trust_remote_code=True, device_map="cuda:1")
def generate(instruction): 
    return instruct_pipeline(instruction)


examples = [
    "Instead of making a peanut butter and jelly sandwich, what else could I combine peanut butter with in a sandwich? Give five ideas",
    "How do I make a campfire?",
    "Write me a tweet about the release of Dolly 2.0, a new LLM"
   
]


def process_example(args):
    for x in generate(args):
        pass
    return x

css = ".generating {visibility: hidden}"

with gr.Blocks(theme=theme, analytics_enabled=False, css=css) as demo:
    with gr.Column():
        gr.Markdown(
            """ ## Dolly 2.0
            Dolly 2.0 is a 12B parameter language model based on the EleutherAI pythia model family and fine-tuned exclusively on a new, high-quality human generated instruction following dataset, crowdsourced among Databricks employees. For more details, please refer to the [model card](https://huggingface.co/databricks/dolly-v2-12b)
            
            Type in the box below and click the button to generate answers to your most pressing questions!
            
      """
        )
        gr.HTML("<p>You can duplicate this Space to run it privately without a queue for shorter queue times  : <a style='display:inline-block' href='https://huggingface.co/spaces/RamAnanth1/Dolly-v2?duplicate=true'><img src='https://img.shields.io/badge/-Duplicate%20Space-blue?labelColor=white&style=flat&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAP5JREFUOE+lk7FqAkEURY+ltunEgFXS2sZGIbXfEPdLlnxJyDdYB62sbbUKpLbVNhyYFzbrrA74YJlh9r079973psed0cvUD4A+4HoCjsA85X0Dfn/RBLBgBDxnQPfAEJgBY+A9gALA4tcbamSzS4xq4FOQAJgCDwV2CPKV8tZAJcAjMMkUe1vX+U+SMhfAJEHasQIWmXNN3abzDwHUrgcRGmYcgKe0bxrblHEB4E/pndMazNpSZGcsZdBlYJcEL9Afo75molJyM2FxmPgmgPqlWNLGfwZGG6UiyEvLzHYDmoPkDDiNm9JR9uboiONcBXrpY1qmgs21x1QwyZcpvxt9NS09PlsPAAAAAElFTkSuQmCC&logoWidth=14' alt='Duplicate Space'></a> </p>")

        with gr.Row():
            with gr.Column(scale=3):
                instruction = gr.Textbox(placeholder="Enter your question here", label="Question", elem_id="q-input")

                with gr.Box():
                    gr.Markdown("**Answer**")
                    output = gr.Markdown(elem_id="q-output")
                submit = gr.Button("Generate", variant="primary")
                gr.Examples(
                    examples=examples,
                    inputs=[instruction],
                    cache_examples=False,
                    fn=process_example,
                    outputs=[output],
                )


    submit.click(generate, inputs=[instruction], outputs=[output])
    instruction.submit(generate, inputs=[instruction], outputs=[output])

demo.queue(concurrency_count=16).launch(debug=True)

```

when running it, this is the error I am getting

![image](https://user-images.githubusercontent.com/19240467/231809515-a65e9cb3-3883-4564-8f84-2b57a3a807b7.png)

```
ValueError: Could not load model F:/Dolly 2.0/dolly-v2-12b with any of the following classes: (<class 
'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 
'transformers.models.gpt_neox.modeling_gpt_neox.GPTNeoXForCausalLM'>).
```

**Comment by FurkanGozukara** [comment]
I have the transformers 4.25.1 and accelerate 0.0.18

any ideas? thank you

@matthayes 

@srowen

@mike-conover-db

@nfx

**Comment by srowen** [comment]
Just search for the error you see, there are several threads on this highlighting different potential causes. Probably you aren't running on sufficient hardware, it's not clear what you are running this on.

**Comment by FurkanGozukara** [comment]
> Just search for the error you see, there are several threads on this highlighting different potential causes. Probably you aren't running on sufficient hardware, it's not clear what you are running this on.

I tried on empty rtx 3060 12 gb

We can't run it on that?

**Comment by srowen** [comment]
Which model, 12B? probably not even in 8-bit. Use a smaller one like the 2.7B param version

**Comment by FurkanGozukara** [comment]
> Which model, 12B? probably not even in 8-bit. Use a smaller one like the 2.7B param version

Yes 12b model

How can I run it in 8bit?

I am trying to learn to make a tutorial video on my channel [SECourses](https://www.youtube.com/SECourses ) 

Can you tell me code ty

**Comment by srowen** [comment]
This is not specific to Dolly. https://huggingface.co/docs/transformers/perf_infer_gpu_one#running-mixedint8-models-single-gpu-setup

**Comment by FurkanGozukara** [comment]
> This is not specific to Dolly. https://huggingface.co/docs/transformers/perf_infer_gpu_one#running-mixedint8-models-single-gpu-setup

Thank you will test

**Comment by FurkanGozukara** [comment]
> This is not specific to Dolly. https://huggingface.co/docs/transformers/perf_infer_gpu_one#running-mixedint8-models-single-gpu-setup

Hello. I tried like this still same error even on 24 GB RTX 3090

`instruct_pipeline = pipeline(model="F:/Dolly 2.0/dolly-v2-12b", load_in_8bit=True, trust_remote_code=True, device_map="cuda:0")
`

![image](https://user-images.githubusercontent.com/19240467/231885879-0180f6a2-16ff-499e-a97c-bb392a1e46e5.png)

**Comment by srowen** [comment]
Are you sure what's in that path is a valid model dir? You have accelerate and bitsandbytes installed?

**Comment by FurkanGozukara** [comment]
> device_map="cuda:0"

the problem was device_map="cuda:0"

this way works

 device_map="auto"
