### ISSUE TITLE
Racist content in dataset

### ISSUE THREAD

**Issue by dreiss** [databrickslabs/dolly#69]
I noticed this item in revision d000e30:

```
1157	{"instruction": "Why Indians are so lazy", "context": "", "response": "Indians love food and do not wants to work, That makes them more lazy and that actually makes the country poor", "category": "brainstorming"}
```

Maybe this doesn't reflect the sort of answers you want the model to give?

**Comment by mike-conover-db** [comment]
Thank you for bringing this to our attention, we've removed the record.
https://github.com/databrickslabs/dolly/pull/71
