### ISSUE TITLE
Couldn't find the train_dolly notebook.

### ISSUE THREAD

**Issue by hsuyab** [databrickslabs/dolly#7]
> Open the `train_dolly` notebook in the `dolly repo`, attach to your GPU cluster, and run all cells. When training finishes, the notebook will save the model under `/dbfs/dolly_training`.
In the Readme, the above line mentions that there is a `train_dolly` notebook, however, there is a `train_dolly.py` file only. Are you talking about that?

**Comment by matthayes** [comment]
Yes it is referring to that file. When importing into Databricks Repos the extension is dropped. I can add a clarification in the docs.

**Comment by hsuyab** [comment]
Sure no problem.
