### ISSUE TITLE
Question: train_dolly.py

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [databrickslabs/dolly#72]
When you run the train_dolly.py file it appears to be using the constant `"tatsu-lab/alpaca"`. So the training script is not actually using the .jsonl file that is included in the data folder, is that correct?

**Comment by Alex-Wenner-FHR** [comment]
It appears that here 
```python
def load_training_dataset(training_data_id: str = DEFAULT_TRAINING_DATASET, split: str = "train") -> Dataset:
``` 
the `training_data_id` is hardcoded to that `"tatsu-lab/alpaca"` value, and when this method is called [here](https://github.com/databrickslabs/dolly/blob/5d3d5cf84bb80337e93984e512afc3a59be1246e/training/trainer.py#L130) there is not an opportunity to pass a parameter or override that without changing code. - I think my thought here is maybe there is an opportunity to exemplify how to use that .jsonl file better - to give users an example to follow when it comes to fine tuning. 

That is if I understand this correctly! Please let me know your thoughts. Thanks.

**Comment by matthayes** [comment]
That's right, the code has not been updated since the dolly v1 release.  But I will be updating it soon to use the jsonl file from the data folder.

**Comment by Alex-Wenner-FHR** [comment]
Great! I will close this with anticipation for that, thank you! @matthayes
