### ISSUE TITLE
Add custom proprietary data to the model

### ISSUE THREAD

**Issue by rajeshjrao** [databrickslabs/dolly#73]
We were able to train the model using train_dolly notebook and it is generating proper responses. How do we add our company's custom proprietary data to model ? I don't need to fine tune the model to do specific tasks but add our custom data to the model's knowledge base so that it can answer questions related to our organization without us providing the input text each time.

For e.g. if we have  a document on internal policies and procedures, we want dolly to give us summary of the policies. How do do this?

**Comment by srowen** [comment]
For that, look into tools like langchain. It can help create a simple system where you embed your text in a vector DB, then find docs similar to a query, put it in a prompt with the question, and send to an LLM.

It's very flexible. You can plug Dolly or other models in as the LLM. You do not need to fine tune on your data at all.

You can do that, just, it isn't actually the easiest way to answer that use case

**Comment by chintan-donda** [comment]
I've similar use case.
How can I fine-tune Dolly with domain specific data like finance, health, agriculture, etc.?
How can we create a domain specific LLM? Say, FinanceLLM, HealthLLM, AgriLLM? Can we do this?

**Comment by srowen** [comment]
See answer above: one answer is that you do not fine-tune the model for this, but supply it with domain information at runtime.
For fine-tuning on custom data, create a dataset like the dolly-15k dataset you see used in this script and point at that instead and run the training script.

**Comment by chintan-donda** [comment]
@srowen Got it. Thanks.
So I need to create the dataset like the dolly-15k format:
```
{
	"instruction": "Which is a species of fish? Tope or Rope",
	"context": "",
	"response": "Tope",
	"category": "classification"
}
```

Will try it and comment here if I face any issue.

**Comment by srowen** [comment]
Well, I'm saying you don't need to fine tune in many cases at all. I wouldn't start there. But yeah if you do, you can match the data set format and fine tune on that. The category is actually not used by the training

**Comment by chintan-donda** [comment]
@srowen Yeah, I've already built a few applications using LangChain, Llama-Index and Chroma/FAISS vector store to create QA, Summarization, Translation on-the-fly.
But my use case is specifically to train the LLM using custom dataset.

**Comment by jackyyanggp** [comment]
@srowen if we fine-tune the model with custom dataset like the dolly-15k and then use that fine-tuned model along with langchain (same dataset as the fine-tune custom dataset mentioned above) like your demo, would it help reduce hallucination issue or improve similarity search results (currently with langchain it's not returning correct results sometimes)?

**Comment by srowen** [comment]
I don't know, depends on your data and how you use it. not sure it helps much with hallucination.
