### ISSUE TITLE
dataset language

### ISSUE THREAD

**Issue by sreekarmolakalapalli** [databrickslabs/dolly#75]
The listed language of the dataset is American English but there are various entries of instructions, context, and responses that contain non-American spellings of words (colour, defence, etc.)

**Comment by srowen** [comment]
The model is fine tuned from a base model that used mostly (American) English language text from the internet. The fine tuning data set is also mostly so. However both of those sources have other languages in them to some extent. American English is the most accurate single description of the total training set.
