### ISSUE TITLE
Dataset:  Inconsistent coding format----   what's & what’s (shown as what\u2019s)

### ISSUE THREAD

**Issue by leemengwei** [databrickslabs/dolly#76]
Hi, thanks to your generousity of the opensource of Finetune dataset of your 5k workers!
Howevery, I notice that there's inconsistent coding format in 15k json dataset, sometimes words with special symbols (' - prounouces etc.) are shown in unicode format sometimes not, e.g :
"instruction": "Alice's parents have three daughters: Amy, Jessy, and what\u2019s the name of the third daughter?"    
in this sentence the 'what's' word must be type as 'what’s'.

Did you notice that? Will it cause any problems?

**Comment by matthayes** [comment]
Hey thanks for raising it. I think it might actually be good for the training data to have these different variations in punctuation so that models trained on it aren’t too rigid in input expectations.
