### ISSUE TITLE
OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by nazkhan-8451** [databrickslabs/dolly#79]
Running on Databricks `generate_text` gives CUDA OOM error after a few runs. I have tried following:
```
with torch.no_grad():
  print(generate_text("Explain to me the difference between nuclear fission and fusion."))
  torch.cuda.empty_cache()
```

Error message: `OutOfMemoryError: CUDA out of memory. Tried to allocate 150.00 MiB (GPU 0; 15.78 GiB total capacity; 14.60 GiB 
already allocated; 9.50 MiB free; 14.64 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory
try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and 
PYTORCH_CUDA_ALLOC_CONF`

**Comment by jdoucette108** [comment]
also getting this error, then the following command produces 
"HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/local_disk0/dolly_training/dolly__2023-04-14T15:45:50'. Use `repo_type` argument if needed."

The specified clusters are not available so i am using the following with num_gpu = 4 and fp16=True,
bf16=False:

1 Driver
448 GB Memory, 24 Cores
Runtime
12.2.x-gpu-ml-scala2.12

**Comment by nazkhan-8451** [comment]
On first try the following gives Cuda OOM error:
```
with torch.no_grad():
  print(generate_text("Give me 10 innovative ideas to start a new business. Give me some details. I should be able to earn atleast 1000$/month using these business."))
  torch.cuda.empty_cache()
```
Using these:
![image](https://user-images.githubusercontent.com/108809950/232115537-eb05ad46-30df-45ff-8c08-da00f9ce579b.png)

**Comment by srowen** [comment]
It's important to pay attention to your GPU size. Those are 16GB V100s. That isn't nearly enough mem to load the 12B model. Load in 8bit, or try a smaller model.

**Comment by sudokhan112** [comment]
3b model works on 16 gb gpu. 12b model doesn't work on 16 gb gpu, even with load_8bit.

**Comment by srowen** [comment]
There's a 7B model that should barely fit on 16GB, comfortably with 8bit.

**Comment by callmesora** [comment]
@srowen  how do you load in 8bit without using the import from outside 

For example in Langchain:

```
hf_pipeline = HuggingFacePipeline(
    pipeline=InstructionTextGenerationPipeline(
        # Return the full text, because this is what the HuggingFacePipeline expects.
        model=model, tokenizer=tokenizer, return_full_text=True, task="text-generation"
  # set the maximum sequence length to 64
    )) # set the batch size to 1)))

llm_chain = LLMChain(llm=hf_pipeline, prompt=prompt)
llm_context_chain = LLMChain(llm=hf_pipeline, prompt=prompt_with_context)
```

**Comment by wqp89324** [comment]
What is the effect of prompt size? I'm running the 3b model locally with a 6GB GPU, which works with short prompt but not with long prompt (CUDA OOM error)? Is there a limitation to the size of prompt?

**Comment by srowen** [comment]
Yes, with that little memory to spare, your prompt length is probably constrained by the input length. It does increase mem usage. The model's maximum should be 2048 tokens, but you will hit it before then I think.
