### ISSUE TITLE
How to repoint code at local model?

### ISSUE THREAD

**Issue by praguepride** [databrickslabs/dolly#80]
Where does the code check for the model? I've already downloaded it directly from hugging face and I don't want to have the code re-download it.

**Comment by nazkhan-8451** [comment]
Yes, facing the same issue. 
```
generate_text = pipeline("text-generation", model="databricks/dolly-v2-12b",trust_remote_code=True,torch_dtype=torch.bfloat16, device_map="auto")

generate_text.save_pretrained("dbfs:/FileStore/shared_uploads/local_folder/dolly_v2")
```

gives: TypeError: Object of type dtype is not JSON serializable

**Comment by srowen** [comment]
What do you mean by where the code checks for a model? are you asking how HF caches it? https://huggingface.co/docs/huggingface_hub/guides/manage-cache 
This is just something HF does automatically.

@nazkhan-8451  that sounds like a separate question, can you use new issues please?
I'm not sure if it's the issue, but you certainly need /dbfs not dbfs: here. If that's not it, does it work on a local path?

**Comment by nazkhan-8451** [comment]
@srowen I was just trying to figure out, when `pipeline` downloads from `model="databricks/dolly-v2-12b"`, how can i save that to dbfs location. Or if I can download it to dbfs and then load it to `pipeline` from dbfs location, that also works. Need the instructions on how to do that.

**Comment by srowen** [comment]
Just:
```
import os
os.environ['TRANSFORMERS_CACHE'] = "/dbfs/..."
```

**Comment by martin-liu** [comment]
Getting the same error `TypeError: Object of type dtype is not JSON serializable`, this seems a bug in `transformers==4.25.1` when serialize with `torch_dtype=torch.bfloat16`, I updated it to latest version (4.28.1) then it works.

@srowen, any specific reason to pin transformers version to `4.25.1`?

**Comment by srowen** [comment]
Probably just because that's what worked, I don't recall seeing that error. But I think it would be fine to pin a later version.

**Comment by srowen** [comment]
Updated to require at least 4.28.1 and updated some other stuff

**Comment by martin-liu** [comment]
Great, thank you very much!
