### ISSUE TITLE
How do you deploy to sagemaker

### ISSUE THREAD

**Issue by avb-is-me** [databrickslabs/dolly#83]
Awesome work on this.  Right now I am trying to deploy this to Sagemaker via the instructions on Hugging Face.  Are those instructions correct?  For reference I am talking about: https://huggingface.co/databricks/dolly-v2-7b.

**Comment by srowen** [comment]
I don't know, you're asking about Hugging Face? this is probably the wrong place to ask, but not clear what you're trying either

**Comment by avb-is-me** [comment]
@srowen Is this the same model related to the model from this post from databricks: https://www.databricks.com/blog/2023/04/12/dolly-first-open-commercially-viable-instruction-tuned-llm.  Usecase is I want to deploy this model to my own Aws environment, aka Sagemaker.  Also hugging face has models from Databricks named Dolly 2.0, which is likely leading to this confusion.  Hope that clarifies.

**Comment by srowen** [comment]
Yes, that is the same model. You can deploy it however you like, it isn't special in this regard. Whatever works for any text-gen model should work on Sagemaker. What is the confusion?

**Comment by avb-is-me** [comment]
@srowen The post refers to https://huggingface.co/databricks.  My main point was when I tried the instructions for one of the models found here: https://huggingface.co/databricks/dolly-v2-7b(click deploy and select sagemaker), there are some errors.  Just wanted to bring that to the team's attention.  For example the instructions mention a machine I think is not powerful enough(it specifies ml.m5.xlarge).  And even when I deploy it to endpoints I get errors.  Realistically might just be me but I would suggest someone else trying it.  Code is below to deploy it.  Let me know if you disagree and think this looks fine as is. 

from sagemaker.huggingface import HuggingFaceModel
import boto3

iam_client = boto3.client('iam')
role = iam_client.get_role(RoleName='{Replace with your aws arn}')['Role']['Arn']
# Hub Model configuration. https://huggingface.co/models
hub = {
	'HF_MODEL_ID':'databricks/dolly-v2-7b',
	'HF_TASK':'text-generation'
}

# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
	transformers_version='4.17.0',
	pytorch_version='1.10.2',
	py_version='py38',
	env=hub,
	role=role, 
)

# deploy model to SageMaker Inference
predictor = huggingface_model.deploy(
	initial_instance_count=1, # number of instances
	instance_type='ml.m5.xlarge' # ec2 instance type
)

predictor.predict({
	'inputs': "Can you please let us know more details about your "
})

**Comment by avb-is-me** [comment]
Also sidenote, totally understand if this is not prioritized but thought it was better to give context for other possible users in a similar situation

**Comment by srowen** [comment]
This is a function of Hugging Face, not of the model or something the project and maintainers control.
That configuration doesn't make sense, its' not even a GPU type. The transformers and pytorch version don't match either.
If you fix that it probably works.

**Comment by avb-is-me** [comment]
@srowen thanks for the clarification.  Makes sense.

**Comment by radsimu** [comment]
Eventually after using better configs 
('transformers_version': '4.26.0',
        'pytorch_version': '1.13.1',
        'py_version': 'py39',
        'instance_type': 'ml.g5.8xlarge'),

I get another issue, apparently, trust_remote_code must be set to True somehow. But given that the model is a prepacked docker image, I don't know how to make it set that to true when calling the prediction pipeline

**Comment by vatsalshah1990** [comment]
@radsimu I'm facing the same issue with trust_remote_code. Let me know if anyone has figured out how to fix this.

**Comment by timesler** [comment]
@radsimu @vatsalshah1990 here is a complete working example that sets `trust_remote_code=True`

https://gist.github.com/timesler/4b244a6b73d6e02d17fd220fd92dfaec

**Comment by srowen** [comment]
Nice thank you!

**Comment by vatsalshah1990** [comment]
Thnaks @timesler. There another way to deploy with DeepSpeed - https://github.com/dhawalkp/dolly-12b/blob/main/dolly-12b-deepspeed-sagemaker.ipynb
