### ISSUE TITLE
Hosting the Dolly dataset on the Hugging Face Hub

### ISSUE THREAD

**Issue by lewtun** [databrickslabs/dolly#86]
Hi Databricks team, this is a really cool project and great job creating a high quality instruction dataset with a permissive license!

Would you be interested in hosting the Dolly dataset on the Hugging Face Hub (https://huggingface.co/datasets)? The Alpaca dataset is also hosted there ([link](https://huggingface.co/datasets/tatsu-lab/alpaca)) and your version would be of wide interest to the community, especially since many people have noted the ToS issues with training on OpenAI model outputs

If that sounds interesting, you just need to create a new dataset repo under the DataBricks [org](https://huggingface.co/databricks) and upload your [databricks-dolly-15k.jsonl](https://github.com/databrickslabs/dolly/blob/master/data/databricks-dolly-15k.jsonl) file through the UI. For more details, you can check out our docs [here](https://huggingface.co/docs/datasets/upload_dataset)

**Comment by srowen** [comment]
I asked, and looks like the plan is to just host it in Github here, for now.
