### ISSUE TITLE
Not able to select an on Azure any GPU machine

### ISSUE THREAD

**Issue by jcsjacekj** [databrickslabs/dolly#9]
Hi.

Trying to run dolly on MS Azure. When I try to create compute cluster, and choosing Runtime 12.2 LTS, cannot choose any GPU machine, like Standard_ND96asr_v4. 
`Error: This node type is not compatible with selected runtime.`
Any suggestions how to resolve this?

**Comment by matthayes** [comment]
Do you have an ML runtime option? For example:

`12.2 LTS ML (includes Apache Spark 3.3.2, GPU, Scala 2.12)`

**Comment by matthayes** [comment]
Also see the comment in #2 in case it is relevant.

**Comment by srowen** [comment]
You need to choose a GPU runtime - and _unselect_ "Use Photon"

**Comment by srowen** [comment]
Closing as duplicate of #2
