### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (863x1 and 11x5120)

### ISSUE THREAD

**Issue by controZheng** [databrickslabs/dolly#90]
Why are you always reporting errors： RuntimeError: mat1 and mat2 shapes cannot be multiplied (863x1 and 11x5120)
![image](https://user-images.githubusercontent.com/42229960/232303689-7da0ef3c-a150-46fd-af0b-3b11c1589e4f.png)

**Comment by srowen** [comment]
Unclear what you are doing here, how you are running it, on what hardware, what changes you might have made, so really hard to say.

**Comment by chi2liu** [comment]
> Why are you always reporting errors： RuntimeError: mat1 and mat2 shapes cannot be multiplied (863x1 and 11x5120) ![image](https://user-images.githubusercontent.com/42229960/232303689-7da0ef3c-a150-46fd-af0b-3b11c1589e4f.png)

@controZheng  how do you solve the issue?

**Comment by srowen** [comment]
How does it arise?
