### ISSUE TITLE
AttributeError: 'str' object has no attribute 'size'

### ISSUE THREAD

**Issue by ibrahim737701** [databrickslabs/dolly#97]
I'm trying to load databricks/dolly-v2-3b using the following code
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("databricks/dolly-v2-3b", padding_side="left")
model = AutoModelForCausalLM.from_pretrained("databricks/dolly-v2-3b", device_map="auto", trust_remote_code=True, torch_dtype=torch.bfloat16)

And it's giving the error, AttributeError: 'str' object has no attribute 'size'

**Comment by srowen** [comment]
Hm, that's working for me. Where does that error occur, this code or elsewhere?
